import test from 'node:test';import assert from 'node:assert/strict';import {eaOperation} from '../extension/ea.js';
function setup({valid=true,owned=false,ambiguous=false,duplicate=false,nonConceptFirst=false,composite=false,saveSuccess=true,variantMetadata=false}={}) {
 const old={id:0,definitionId:0,concept:false,isValid:()=>false};const slot={index:0,generalPositionName:'GK',item:owned?{...old,id:5,isValid:()=>true}:old};
 const concept={id:composite?50577890:123,assetId:composite?undefined:10,definitionId:composite?50577890:10,rating:composite?78:83,rareflag:0,concept:true,isValid:()=>true,...(variantMetadata?{teamId:693,leagueId:39,nationId:37,preferredPosition:16}:{})};let saved=0,opened=0;
 const squad={getNonBrickSlots:()=>[slot],getFormation:()=>({displayName:'4-3-3'}),addItemToSlot:(_,i)=>slot.item=i};
 const challenge={id:59,name:'Challenge',squad,hasExpired:()=>false,isCompleted:()=>false,meetsRequirements:()=>valid};
 const nav={getCurrentController:()=>({_challenge:challenge}),pushViewController:()=>opened++};
 globalThis.window={fut_year:'2027'};globalThis.getAppMain=()=>({getRootViewController:()=>({getPresentedViewController:()=>({getCurrentViewController:()=>nav})})});
 const obs=result=>({observe(owner,fn){queueMicrotask(()=>fn(this,result));},unobserve(){}});
 const results=ambiguous?[concept,{...concept,id:124,definitionId:11,...(variantMetadata?{teamId:694}:{})}]:duplicate?[concept,{...concept,id:124}]:nonConceptFirst?[{...concept,concept:false},concept]:[concept];
 globalThis.services={User:{getUser:()=>({getSelectedPersona:()=>({getCurrentClub:()=>({isPlaystation:true})})})},Club:{search:()=>obs({success:true,response:{items:[],retrievedAll:true}})},Item:{searchConceptItems:()=>obs({success:true,response:{items:results}}),clearTransferMarketCache(){}},SBC:{saveChallenge:()=>{saved++;return obs({success:saveSuccess,status:500});}}};
 globalThis.UTSearchCriteriaDTO=class{};globalThis.SearchType={PLAYER:'player'};globalThis.UTMarketSearchResultsViewController=class{initWithSearchCriteria(c){assert.deepEqual(c.defId,[10]);}};
 return {slot,old,challenge,get saved(){return saved;},get opened(){return opened;}};
}
const player={baseId:10,definitionId:10,rating:83,rarity:0,name:'Player'};
const observed=result=>({observe(owner,fn){queueMicrotask(()=>fn(this,result));},unobserve(){}});
async function payload(){return {challengeId:59,players:[player],mapping:[0],fingerprint:(await eaOperation('status')).challenge.fingerprint};}
test('resolves one card definition even when EA returns duplicate concept rows',async()=>{setup({duplicate:true});assert.equal((await eaOperation('resolve',{challengeId:59,players:[player]})).players[0].definitionId,10);});
test('matches Dia when EA only supplies a composite definition ID',async()=>{const env=setup({composite:true});const dia={baseId:246242,rating:78,rarity:0,name:'Boulaye Dia'};const resolved=await eaOperation('resolve',{challengeId:59,players:[dia]});assert.equal(resolved.players[0].definitionId,50577890);const added=await eaOperation('concepts',{challengeId:59,players:resolved.players,mapping:[0],fingerprint:resolved.challenge.fingerprint});assert.equal(added.ok,true);assert.equal(env.saved,1);});
test('rejects genuinely different matching card definitions without changing the squad',async()=>{const env=setup({ambiguous:true});const result=await eaOperation('resolve',{challengeId:59,players:[player]});assert.equal(result.ok,false);assert.match(result.error,/2 distinct EA cards/);assert.equal(env.slot.item,env.old);assert.equal(env.saved,0);});
test('uses FUTBIN club, league, nation and position to resolve same-rated EA variants',async()=>{const env=setup({ambiguous:true,variantMetadata:true});const identified={...player,clubId:693,leagueId:39,nationId:37,position:'LM'};const resolved=await eaOperation('resolve',{challengeId:59,players:[identified]});assert.equal(resolved.ok,true);assert.equal(resolved.players[0].definitionId,10);const added=await eaOperation('concepts',{challengeId:59,players:resolved.players,mapping:[0],fingerprint:resolved.challenge.fingerprint});assert.equal(added.ok,true);assert.equal(env.saved,1);});
test('a unique EA card remains matchable when FUTBIN club metadata is stale',async()=>{const env=setup({variantMetadata:true});const stale={...player,clubId:999,leagueId:999,nationId:37};const resolved=await eaOperation('resolve',{challengeId:59,players:[stale]});assert.equal(resolved.ok,true);assert.equal(resolved.players[0].definitionId,10);const added=await eaOperation('concepts',{challengeId:59,players:resolved.players,mapping:[0],fingerprint:resolved.challenge.fingerprint});assert.equal(added.ok,true);assert.equal(env.saved,1);});
test('a stale FUTBIN club still cannot bypass EA SBC requirements',async()=>{const env=setup({variantMetadata:true,valid:false});const stale={...player,clubId:999,leagueId:999,nationId:37};const resolved=await eaOperation('resolve',{challengeId:59,players:[stale]});assert.equal(resolved.ok,true);const added=await eaOperation('concepts',{challengeId:59,players:resolved.players,mapping:[0],fingerprint:resolved.challenge.fingerprint});assert.equal(added.ok,false);assert.equal(env.slot.item,env.old);assert.equal(env.saved,0);});
test('stale metadata does not permit a different rarity',async()=>{setup({variantMetadata:true});const result=await eaOperation('resolve',{challengeId:59,players:[{...player,clubId:999,rarity:1}]});assert.equal(result.ok,false);assert.equal(result.unmatchedPlayer.baseId,10);assert.match(result.error,/different rarity/);});
test('accepts a FUTBIN squad position that is an EA alternate position',async()=>{setup();services.Item.searchConceptItems=()=>({observe(owner,fn){queueMicrotask(()=>fn(this,{success:true,response:{items:[{assetId:10,definitionId:10,rating:83,rareflag:0,concept:true,teamId:693,preferredPosition:27,basePossiblePositions:[27,16]}]}}));},unobserve(){}});const result=await eaOperation('resolve',{challengeId:59,players:[{...player,clubId:693,position:'LM'}]});assert.equal(result.players[0].definitionId,10);});
test('does not reject a unique concept merely because FUTBIN places it out of position',async()=>{setup();services.Item.searchConceptItems=()=>({observe(owner,fn){queueMicrotask(()=>fn(this,{success:true,response:{items:[{assetId:10,definitionId:10,rating:83,rareflag:0,concept:true,preferredPosition:27,basePossiblePositions:[27]}]}}));},unobserve(){}});const result=await eaOperation('resolve',{challengeId:59,players:[{...player,position:'LM'}]});assert.equal(result.players[0].definitionId,10);});
test('face stats distinguish two otherwise identical concept cards',async()=>{setup({ambiguous:true,variantMetadata:true});const identified={...player,clubId:693,leagueId:39,nationId:37,position:'LM',attributes:[59,50,45,60,24,46]};services.Item.searchConceptItems=()=>({observe(owner,fn){queueMicrotask(()=>fn(this,{success:true,response:{items:[{assetId:10,definitionId:10,rating:83,rareflag:0,concept:true,teamId:693,leagueId:39,nationId:37,preferredPosition:16,attributes:[59,50,45,60,24,46]},{assetId:10,definitionId:11,rating:83,rareflag:0,concept:true,teamId:693,leagueId:39,nationId:37,preferredPosition:16,attributes:[60,50,45,60,24,46]}]}}));},unobserve(){}});const result=await eaOperation('resolve',{challengeId:59,players:[identified]});assert.equal(result.players[0].definitionId,10);});
test('queries multiple concepts together when EA returns the complete batch',async()=>{setup();const requested=[];services.Item.searchConceptItems=criteria=>{requested.push(criteria.defId);return {observe(owner,fn){queueMicrotask(()=>fn(this,{success:true,response:{items:[{assetId:10,definitionId:10,rating:83,rareflag:0,concept:true},{assetId:20,definitionId:20,rating:82,rareflag:0,concept:true}]}}));},unobserve(){}};};const result=await eaOperation('resolve',{challengeId:59,players:[player,{baseId:20,rating:82,rarity:0,name:'Second'}]});assert.deepEqual(result.players.map(p=>p.definitionId),[10,20]);assert.deepEqual(requested,[[10,20]]);});
test('checks later EA concept pages before declaring a card unavailable',async()=>{setup();const offsets=[];services.Item.searchConceptItems=criteria=>{offsets.push(criteria.offset);const items=criteria.offset?[{assetId:10,definitionId:10,rating:83,rareflag:0,concept:true}]:Array.from({length:20},(_,index)=>({assetId:1000+index,definitionId:1000+index,rating:83,rareflag:0,concept:true}));return observed({success:true,response:{items,endOfList:!!criteria.offset}});};const result=await eaOperation('resolve',{challengeId:59,players:[player]});assert.equal(result.ok,true,result.error);assert.deepEqual(offsets,[0,20]);});
test('fails closed when FUTBIN and EA club IDs disagree',async()=>{const env=setup({ambiguous:true,variantMetadata:true});const result=await eaOperation('resolve',{challengeId:59,players:[{...player,clubId:999,position:'LM'}]});assert.equal(result.ok,false);assert.match(result.error,/0 distinct EA cards/);assert.equal(env.saved,0);});
test('insertion chooses the concept copy when EA also returns a non-concept row',async()=>{const env=setup({nonConceptFirst:true});assert.equal((await eaOperation('concepts',await payload())).ok,true);assert.equal(env.slot.item.concept,true);});
test('inserts valid concepts and saves once',async()=>{const env=setup();assert.equal((await eaOperation('concepts',await payload())).ok,true);assert.equal(env.saved,1);assert.equal(env.slot.item.concept,true);});
test('uses an exact owned card before loading its concept',async()=>{const env=setup();const owned={id:700,assetId:10,definitionId:10,rating:83,rareflag:0,concept:false,isValid:()=>true};let conceptSearches=0;services.Club.search=criteria=>{assert.deepEqual(criteria.defId,[10]);assert.equal(criteria.type,'player');return {observe(owner,fn){queueMicrotask(()=>fn(this,{success:true,response:{items:[owned],retrievedAll:true}}));},unobserve(){}};};services.Item.searchConceptItems=()=>{conceptSearches++;throw Error('Concept search should be skipped');};const result=await eaOperation('concepts',await payload());assert.equal(result.ok,true);assert.equal(result.players[0].owned,true);assert.equal(env.slot.item,owned);assert.equal(env.saved,1);assert.equal(conceptSearches,0);});
test('ignores a different club card and uses the matched concept',async()=>{const env=setup();services.Club.search=()=>({observe(owner,fn){queueMicrotask(()=>fn(this,{success:true,response:{items:[{id:701,assetId:10,definitionId:11,rating:83,rareflag:0,concept:false}],retrievedAll:true}}));},unobserve(){}});const result=await eaOperation('concepts',await payload());assert.equal(result.ok,true);assert.equal(result.players[0].owned,false);assert.equal(env.slot.item.concept,true);});
test('club search failure does not insert a concept or save the SBC',async()=>{const env=setup();services.Club.search=()=>({observe(owner,fn){queueMicrotask(()=>fn(this,{success:false,status:500}));},unobserve(){}});const result=await eaOperation('concepts',await payload());assert.equal(result.ok,false);assert.equal(env.slot.item,env.old);assert.equal(env.saved,0);});
test('checks later club pages before falling back to a concept',async()=>{const env=setup();const offsets=[];const owned={id:704,assetId:10,definitionId:10,rating:83,rareflag:0,concept:false,isValid:()=>true};services.Club.search=criteria=>{offsets.push(criteria.offset);const response=criteria.offset?{items:[owned],retrievedAll:true}:{items:[{id:900,definitionId:99,concept:false}],retrievedAll:false};return {observe(owner,fn){queueMicrotask(()=>fn(this,{success:true,response}));},unobserve(){}};};const result=await eaOperation('concepts',await payload());assert.equal(result.ok,true);assert.deepEqual(offsets,[0,1]);assert.equal(env.slot.item,owned);});
test('an already placed matching owned card is retained',async()=>{const env=setup();const owned={id:702,assetId:10,definitionId:10,rating:83,rareflag:0,concept:false,isValid:()=>true};env.slot.item=owned;const result=await eaOperation('concepts',await payload());assert.equal(result.ok,true);assert.equal(result.players[0].owned,true);assert.equal(env.slot.item,owned);assert.equal(env.saved,1);});
test('one owned copy fills only one of two matching slots',async()=>{const env=setup();const second={index:1,generalPositionName:'ST',item:{id:0,definitionId:0,concept:false,isValid:()=>false}};env.challenge.squad.getNonBrickSlots=()=>[env.slot,second];env.challenge.squad.addItemToSlot=(index,item)=>[env.slot,second][index].item=item;const owned={id:703,assetId:10,definitionId:10,rating:83,rareflag:0,concept:false,isValid:()=>true};services.Club.search=()=>({observe(owner,fn){queueMicrotask(()=>fn(this,{success:true,response:{items:[owned],retrievedAll:true}}));},unobserve(){}});const result=await eaOperation('concepts',{challengeId:59,players:[player,{...player,name:'Second'}],mapping:[0,1],fingerprint:(await eaOperation('status')).challenge.fingerprint});assert.equal(result.ok,true);assert.deepEqual(result.players.map(p=>p.owned),[true,false]);assert.equal(env.slot.item,owned);assert.equal(second.item.concept,true);});
test('invalid requirements restore squad without saving',async()=>{const env=setup({valid:false});assert.equal((await eaOperation('concepts',await payload())).ok,false);assert.equal(env.slot.item,env.old);assert.equal(env.saved,0);});
test('failed save restores local squad',async()=>{const env=setup({saveSuccess:false});assert.equal((await eaOperation('concepts',await payload())).ok,false);assert.equal(env.slot.item,env.old);});
test('owned players and changed challenges block insertion',async()=>{const env=setup({owned:true});assert.equal((await eaOperation('concepts',await payload())).ok,false);assert.equal(env.saved,0);setup();assert.equal((await eaOperation('concepts',{...await payload(),challengeId:999})).ok,false);assert.equal((await eaOperation('concepts',{...await payload(),fingerprint:'old'})).ok,false);});
test('shopping opens EA exact-card results and does not transact',async()=>{const env=setup();assert.equal((await eaOperation('market',{player})).ok,true);assert.equal(env.opened,1);assert.equal(env.saved,0);});
test('swap check restores the SBC and swap apply saves only a valid replacement',async()=>{const env=setup();const request={challengeId:59,fingerprint:(await eaOperation('status')).challenge.fingerprint,slotIndex:0,player};const checked=await eaOperation('sbcSwapCheck',request);assert.equal(checked.valid,true);assert.equal(env.slot.item,env.old);assert.equal(env.saved,0);const applied=await eaOperation('sbcSwapApply',request);assert.equal(applied.ok,true);assert.equal(env.slot.item.concept,true);assert.equal(env.saved,1);});
test('an invalid swap leaves the original SBC untouched',async()=>{const env=setup({valid:false});const request={challengeId:59,fingerprint:(await eaOperation('status')).challenge.fingerprint,slotIndex:0,player};const checked=await eaOperation('sbcSwapCheck',request);assert.equal(checked.valid,false);assert.equal(env.slot.item,env.old);assert.equal((await eaOperation('sbcSwapApply',request)).ok,false);assert.equal(env.slot.item,env.old);assert.equal(env.saved,0);});
test('live SBC quote selects the lowest exact-card buy-now listing',async()=>{setup();services.User.getUser=()=>({getSelectedPersona:()=>({getCurrentClub:()=>({isPlaystation:true})}),getCurrency:()=>({amount:1000})});globalThis.GameCurrency={COINS:'coins'};const listing=price=>({id:price,assetId:10,definitionId:10,rating:83,rareflag:0,concept:false,isPlayer:()=>true,getAuctionData:()=>({tradeId:price,buyNowPrice:price,getSecondsRemaining:()=>90,canBuy:()=>true})});services.Item.searchTransferMarket=()=>observed({success:true,data:{items:[listing(600),listing(450)]}});const result=await eaOperation('sbcQuote',{challengeId:59,player});assert.equal(result.phase,'quoted');assert.equal(result.price,450);assert.equal(result.tradeId,'450');});
test('SBC buyer buys within the quote, sends to club, and verifies the exact item',async()=>{setup();let balance=1000,moved=false;services.User.getUser=()=>({getSelectedPersona:()=>({getCurrentClub:()=>({isPlaystation:true})}),getCurrency:()=>({amount:balance})});globalThis.GameCurrency={COINS:'coins'};globalThis.ItemPile={PURCHASED:6,CLUB:7};const auction={tradeId:900,buyNowPrice:450,getSecondsRemaining:()=>90,canBuy:()=>true,isWon:()=>false};const listing={id:900,assetId:10,definitionId:10,rating:83,rareflag:0,concept:false,isPlayer:()=>true,getAuctionData:()=>auction};const won={...listing,id:901,pile:6,getAuctionData:()=>({...auction,isWon:()=>true})};services.Item.searchTransferMarket=()=>observed({success:true,data:{items:[listing]}});services.Item.bid=(item,price)=>{assert.equal(item,listing);assert.equal(price,450);balance-=price;return observed({success:true,data:{items:[won]}});};services.Item.move=(item,pile)=>{assert.equal(item,won);assert.equal(pile,7);moved=true;return observed({success:true});};services.Club.search=()=>observed({success:true,response:{items:moved?[won]:[],retrievedAll:true}});const result=await eaOperation('sbcBuyOne',{challengeId:59,player,maxPrice:450,remaining:450});assert.equal(result.phase,'in-club');assert.equal(result.price,450);assert.equal(result.balance,550);assert.equal(moved,true);});
test('uncertain SBC purchase does not send an unverified card to club',async()=>{setup();services.User.getUser=()=>({getSelectedPersona:()=>({getCurrentClub:()=>({isPlaystation:true})}),getCurrency:()=>({amount:1000})});globalThis.GameCurrency={COINS:'coins'};globalThis.ItemPile={PURCHASED:6,CLUB:7};const listing={id:900,assetId:10,definitionId:10,rating:83,rareflag:0,concept:false,isPlayer:()=>true,getAuctionData:()=>({tradeId:900,buyNowPrice:450,getSecondsRemaining:()=>90,canBuy:()=>true,isWon:()=>false})};services.Item.searchTransferMarket=()=>observed({success:true,data:{items:[listing]}});services.Item.bid=()=>observed({success:true,data:{items:[]}});services.Item.move=()=>{throw Error('Must not move');};const result=await eaOperation('sbcBuyOne',{challengeId:59,player,maxPrice:450,remaining:450});assert.equal(result.phase,'uncertain');});

test("PC club is rejected before EA actions",async()=>{setup();services.User.getUser=()=>({getSelectedPersona:()=>({getCurrentClub:()=>({isPC:true})})});assert.equal((await eaOperation("status")).ok,false);});


test('SBC quote identifies an EA search rejection without attempting a purchase',async()=>{
 setup();
 services.User.getUser=()=>({getSelectedPersona:()=>({getCurrentClub:()=>({isPlaystation:true})}),getCurrency:()=>({amount:1000})});
 globalThis.GameCurrency={COINS:'coins'};
 services.Item.searchTransferMarket=()=>observed({success:false,status:521});
 services.Item.bid=()=>{throw Error('Must not buy');};
 const result=await eaOperation('sbcQuote',{challengeId:59,player});
 assert.equal(result.ok,false);
 assert.equal(result.stage,'sbc-price');
 assert.equal(result.page,1);
 assert.equal(result.status,521);
 assert.match(result.error,/Market page 1.*521/);
});
