import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {JSDOM} from 'jsdom';
test('Gallery displays card pictures, skips club cards, and buys only after an explicit budgeted click',async()=>{
 const html=await readFile(new URL('../extension/panel.html',import.meta.url),'utf8'),script='const renderPortfolio=()=>{};\n'+(await readFile(new URL('../extension/panel.js',import.meta.url),'utf8')).replace(/^import .*\n/gm,'');
 const dom=new JSDOM(html,{url:'https://extension.test/panel.html',runScripts:'outside-only'}),calls=[];
 const plan={id:'gallery-plan',name:'Example Gallery',grade:'D',balance:5000,computedAt:Date.now(),source:'FUT.GG',estimatedScore:1500,tokens:0,players:[{definitionId:1,name:'Owned player',rating:80,position:'GK',phase:'owned',price:650},{definitionId:2,name:'A long player name with a card picture',rating:78,position:'CM',phase:'missing',price:700,picture:'https://game-assets.fut.gg/2027/card.webp'}]};
 dom.window.chrome={runtime:{id:'test',sendMessage:async message=>{calls.push(message);if(message.type==='galleryState')return {ok:true,data:plan};if(message.type==='galleryPaletools')return {ok:true,data:{...plan,collectionSource:'Paletools'}};if(message.type==='galleryCatalogue')return {ok:true,data:[{name:'Example Gallery',category:'League',requiredCards:15,url:'https://www.fut.gg/fut-gallery/laliga/rayo-vallecano/'}]};if(message.type==='galleryStart')return {ok:true,data:{...plan,enabled:true,status:'Collecting…'}};return {ok:true,data:{}};}},storage:{onChanged:{addListener(){}}}};
 try{
  dom.window.eval(script);const doc=dom.window.document;doc.getElementById('gallery-tab').click();await new Promise(resolve=>setImmediate(resolve));
  assert.equal(doc.getElementById('gallery-view').hidden,false);assert.equal(doc.getElementById('team-view').hidden,true);assert.match(doc.getElementById('gallery-count').textContent,/1 \/ 2/);assert.equal(doc.querySelector('.gallery-card input[type=checkbox]').disabled,true);assert.equal(doc.querySelectorAll('.gallery-card input[type=number]').length,1);assert.equal(doc.querySelector('.gallery-card img').src,plan.players[1].picture);assert.equal(calls.some(c=>c.type==='galleryStart'),false);
  doc.getElementById('gallery-paletools').click();await new Promise(resolve=>setImmediate(resolve));assert.equal(calls.find(c=>c.type==='galleryPaletools').grade,'D');assert.match(doc.getElementById('gallery-evidence').textContent,/Paletools collection/);assert.equal(calls.some(c=>c.type==='galleryStart'),false);
  doc.querySelector('.gallery-card input[type=number]').value='800';doc.querySelector('.gallery-card input[type=number]').dispatchEvent(new dom.window.Event('input'));doc.getElementById('gallery-budget').value='1000';doc.getElementById('gallery-start').click();await new Promise(resolve=>setImmediate(resolve));
  const buy=calls.find(c=>c.type==='galleryStart');assert.equal(buy.planId,'gallery-plan');assert.equal(buy.budget,1000);assert.equal(buy.caps[2],800);assert.equal(doc.getElementById('gallery-stop').hidden,false);assert.equal(doc.getElementById('gallery-start').disabled,true);assert.equal(doc.getElementById('gallery-paletools').disabled,true);
 }finally{dom.window.close();}
});
